### ISSUE TITLE
Add roles for microservice endpoints 

### ISSUE THREAD

**Issue by switschel** [SoftwareAG/cumulocity-dynamic-mqtt-mapper#33]
We should secure the REST endpoints with at least 1 or 2 roles.
ADMIN - can make configuration changes to MQTT Broker config etc.
USER - can add/edit/delete mappings

We could also make this more sophisticated but that makes it much more complex to assign the correct roles to the users.

**Comment by sagIoTPower** [comment]
Hi @switschel 
I implemented this feature and added roles:
```
  "roles":[
    "ROLE_MQTT_MAPPING_ADMIN",
    "ROLE_MQTT_MAPPING_CREATE"
  ]
```
to `cumulocity.json` in commit a41dfac50ccfffcca9968fb82482c73b44a61fde.

The UI tabs:
1. `Configuration`
2. `Processor Extension`
 are restricted to users with role `ROLE_MQTT_MAPPING_ADMIN`.
