### ISSUE TITLE
Mapping of json keys 

### ISSUE THREAD

**Issue by simeonthefirst** [SoftwareAG/cumulocity-dynamic-mqtt-mapper#34]
I have a usecase, where there are many different measurements and more may also be added over time. To help that i don't want to have a mapping for each measurement, but only one dynamic mapping that covers that.

Threfore i have to map the keys of the source message (eg. /devicename/_measurementname_ { "_series-name_": 12 }  ) to the mqtt message format of cumulocity where the measurement name and series names are keys not values . In this example from a topic to a json key (` [ _TOPIC_LEVEL_[1] -> $keys()[3] ]`  ) and from a json key to a json key for the series name:  `[ $keys()[0] -> $keys($eval($keys()[3]))[0] ]` .
To put the value into the series i used: `[ $eval($keys($)[0]) -> **.value[0] ] `

I know that with that kind of mapping the order of the fragments is relevant what is not json like but i think thats the only option. 

I have no experience with jsonata but my queries worked in the online jsonata tester (https://try.jsonata.org/) .  The testing in the c8y app seems to have failed (screenshot). 
![image](https://github.com/SoftwareAG/cumulocity-dynamic-mqtt-mapper/assets/50956501/c9a7dc07-be52-4687-916b-a7a3463f81e2)

Is it in somehow possible to map the keys or is this service limited to value mapping?

**Comment by switschel** [comment]
Hm we can investigate that but full generic mappings are always very dangerous. A lot of bad stuff can happen when using it. Our core concept is that we use a specific topic as a key for a mapping. So when the topic is `/devicename/measurementname` the payload including keys should always be the same (except the values of course).
You can also use a template where you define all possible keys by hand and map them accordingly in just one mapping.

**Comment by sagIoTPower** [comment]
Hi @simeonthefirst ,

you can try to use the following sample, to generate dynamicaliy new nodes:

![Screenshot 2023-07-03 at 18 08 35](https://github.com/SoftwareAG/cumulocity-dynamic-mqtt-mapper/assets/29702059/0c7e036d-624c-4e37-ab35-720ba0782709)

This will transform the source msg. as follows:
![Screenshot 2023-07-03 at 18 08 15](https://github.com/SoftwareAG/cumulocity-dynamic-mqtt-mapper/assets/29702059/f27de784-e1b4-4197-a2d2-ad8e44f649e9)

If your mapping requires more flexibility, then I recommend using the programmatic approach. This means writing your own mapping class in Java and upload this to the mapper. A sample implementation can be found [here](https://github.com/SoftwareAG/cumulocity-dynamic-mqtt-mapper/tree/main/mqtt-mapping-extension/src/main/java/mqtt/mapping/processor/extension/external).
The extension mechanism is documented [here](https://github.com/SoftwareAG/cumulocity-dynamic-mqtt-mapper#processing-extensions).

Pls. let me know if this helps.

--Christof

**Comment by simeonthefirst** [comment]
Hi,
thank you ! Your exampe, @sagIoTPower gives the flexibility to ignore the key-string on the device-side message what is part of what i wanted to achieve. 
It does not enable me to change the measurement or series name on cumulocity side of the mapping. To realize a mapping like this (see below) , i will need to implement an extension. I will let you know when i do. 

```
(device side)
{
 "Measurementname": "Airsensor",
 "Seriesename":"Humidity",
 "value":10,
 "unit":"%",
}
-->
(cumulocity side)
{
  "Airsensor": {
    "Humidity": {
      "unit": "%",
      "value": 10
    }
  }
 "time": ....
...
}
`````

**Comment by sagIoTPower** [comment]
Hi @simeonthefirst,

I added a new setting `RepaiStrategy = REMOVE_IF_NULL` and added a [sample](https://github.com/SoftwareAG/cumulocity-dynamic-mqtt-mapper/blob/main/resources/script/mapping/sampleMapping/Sample%20Mappings%2006.pdf), mapping number 23 ( flexMeasurement).

Could you pls. take a look if this helps and fits for your use case?

Regards Christof

**Comment by simeonthefirst** [comment]
Hi @sagIoTPower ,

thank you! I did not had the time to test it jet, but took a look at the example. For me it looks like the measurement-/fragmentname can now vary between different pre-known names. Or do i get it wrong? 
More important for me would be to set the measurement-/fragmentname and/or also series name to something you don't now at the time when you create the mapping. I'm sorry if this was a misunderstanding.

best regards,
Simeon
