### ISSUE TITLE
Capability of modifying the root of the message

### ISSUE THREAD

**Issue by sagjoin** [SoftwareAG/cumulocity-dynamic-mqtt-mapper#57]
Dear awesome team,

It would be really great if there's a possibility of editing the root of the message in order to create custom JSON measurements based even in the type get from a MQTT message. For one use case we do have a JSON input like: 

{
  "values": [
    {
      "key": "velocidad_cabezal",
      "value": 136.34
    },
	{
		"key":"temperature",
		"value":25
	}
  ],
  "_TOPIC_LEVEL_": [
    "v2",
    "things",
    "test"
  ]
}

And the idea is to be able to create an output like: 

{
  "time": "2023-10-31T11:11:23.747Z",
  "source": {
    "id": "9299280"
  },
  "type": "c8y_DynamicMeasurement",
  "c8y_velocidad_cabezal": {
    "Measurement": {
      "value": 1211.34,
      "key": "U"
    }
  },
  "c8y_temperature": {
    "Measurement": {
      "value": 230,
      "key": "U"
    }
  },
  "id": "983171",
  "lastUpdated": "2023-10-31T11:11:23.752Z"
}

**Comment by sagIoTPower** [comment]
This is a great requirement and it is addressed in release[ v.3.3.2 ](https://github.com/SoftwareAG/cumulocity-dynamic-mqtt-mapper/releases/tag/v.3.3.2)
